//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18046
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace RecordsViewer.Portable.Resources {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RecordsViewer.Portable.Resources.Strings", typeof(Strings).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Records Viewer 的本地化字符串。
        /// </summary>
        public static string AppTitle {
            get {
                return ResourceManager.GetString("AppTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Do you want to exit Records Viewer? 的本地化字符串。
        /// </summary>
        public static string Exit_Message {
            get {
                return ResourceManager.GetString("Exit_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Exit Records Viewer 的本地化字符串。
        /// </summary>
        public static string Exit_Title {
            get {
                return ResourceManager.GetString("Exit_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Agency 的本地化字符串。
        /// </summary>
        public static string Login_Agency {
            get {
                return ResourceManager.GetString("Login_Agency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Environment 的本地化字符串。
        /// </summary>
        public static string Login_Environment {
            get {
                return ResourceManager.GetString("Login_Environment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Login Failure 的本地化字符串。
        /// </summary>
        public static string Login_Error_Message_Title {
            get {
                return ResourceManager.GetString("Login_Error_Message_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Agency, Username and Password are required. 的本地化字符串。
        /// </summary>
        public static string Login_Field_Empty_Message {
            get {
                return ResourceManager.GetString("Login_Field_Empty_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Password 的本地化字符串。
        /// </summary>
        public static string Login_Password {
            get {
                return ResourceManager.GetString("Login_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Sign In 的本地化字符串。
        /// </summary>
        public static string Login_SignIn {
            get {
                return ResourceManager.GetString("Login_SignIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Sign Out 的本地化字符串。
        /// </summary>
        public static string Login_SignOut {
            get {
                return ResourceManager.GetString("Login_SignOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Username 的本地化字符串。
        /// </summary>
        public static string Login_Username {
            get {
                return ResourceManager.GetString("Login_Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 List 的本地化字符串。
        /// </summary>
        public static string Map_List {
            get {
                return ResourceManager.GetString("Map_List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 This app accesses your phone&apos;s location. Is that ok? 的本地化字符串。
        /// </summary>
        public static string Map_LocationConsent_Message {
            get {
                return ResourceManager.GetString("Map_LocationConsent_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Location 的本地化字符串。
        /// </summary>
        public static string Map_LocationConsent_Title {
            get {
                return ResourceManager.GetString("Map_LocationConsent_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Me 的本地化字符串。
        /// </summary>
        public static string Map_Me {
            get {
                return ResourceManager.GetString("Map_Me", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Reload 的本地化字符串。
        /// </summary>
        public static string Map_Reload {
            get {
                return ResourceManager.GetString("Map_Reload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Settings 的本地化字符串。
        /// </summary>
        public static string Map_Settings {
            get {
                return ResourceManager.GetString("Map_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Description: 的本地化字符串。
        /// </summary>
        public static string Record_Label_Description {
            get {
                return ResourceManager.GetString("Record_Label_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Record ID: 的本地化字符串。
        /// </summary>
        public static string Record_Label_ID {
            get {
                return ResourceManager.GetString("Record_Label_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Record Name: 的本地化字符串。
        /// </summary>
        public static string Record_Label_Name {
            get {
                return ResourceManager.GetString("Record_Label_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Open Date: 的本地化字符串。
        /// </summary>
        public static string Record_Label_OpenDate {
            get {
                return ResourceManager.GetString("Record_Label_OpenDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Status: 的本地化字符串。
        /// </summary>
        public static string Record_Label_Status {
            get {
                return ResourceManager.GetString("Record_Label_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Record Type: 的本地化字符串。
        /// </summary>
        public static string Record_Label_Type {
            get {
                return ResourceManager.GetString("Record_Label_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Record Detail 的本地化字符串。
        /// </summary>
        public static string Record_Title {
            get {
                return ResourceManager.GetString("Record_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Load failed 的本地化字符串。
        /// </summary>
        public static string Records_Error_Message_Title {
            get {
                return ResourceManager.GetString("Records_Error_Message_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Map 的本地化字符串。
        /// </summary>
        public static string Records_Map {
            get {
                return ResourceManager.GetString("Records_Map", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Refresh 的本地化字符串。
        /// </summary>
        public static string Records_Map_Refresh {
            get {
                return ResourceManager.GetString("Records_Map_Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Record List 的本地化字符串。
        /// </summary>
        public static string Records_Title {
            get {
                return ResourceManager.GetString("Records_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 LeftToRight 的本地化字符串。
        /// </summary>
        public static string ResourceFlowDirection {
            get {
                return ResourceManager.GetString("ResourceFlowDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 en-us 的本地化字符串。
        /// </summary>
        public static string ResourceLanguage {
            get {
                return ResourceManager.GetString("ResourceLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Location Services 的本地化字符串。
        /// </summary>
        public static string Settings_Label_Location {
            get {
                return ResourceManager.GetString("Settings_Label_Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Map Zoom Control 的本地化字符串。
        /// </summary>
        public static string Settings_Label_MapZoom {
            get {
                return ResourceManager.GetString("Settings_Label_MapZoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Settings 的本地化字符串。
        /// </summary>
        public static string Settings_Title {
            get {
                return ResourceManager.GetString("Settings_Title", resourceCulture);
            }
        }
    }
}
